name = "LowRankLayers"
uuid = "b66182ab-a85c-43b0-99bd-d85cc47c5e50"
authors = ["murrellb <murrellb@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"

[compat]
Flux = "0.14"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
